require 'watir'
require 'watir-webdriver'
require 'nokogiri'
require 'pry'
require 'ap'
# TODO(dariaev): add dependencies 
chromedriver_path = '/Users/ethanbarhydt/Documents/browsers/chromedriver'
Selenium::WebDriver::Chrome.driver_path = chromedriver_path
require_relative './smccrawler/base_crawler'
# require 'smccrawler/employee_state_extractor/al'
# require 'smccrawler/employee_state_extractor/az'
# require 'smccrawler/employee_state_extractor/ca'
# require 'smccrawler/employee_state_extractor/co'
# require 'smccrawler/employee_state_extractor/ct'
# require 'smccrawler/employee_state_extractor/dc'
# require 'smccrawler/employee_state_extractor/de'
# require 'smccrawler/employee_state_extractor/fl'
# require 'smccrawler/employee_state_extractor/ga'
# require 'smccrawler/employee_state_extractor/ia'
# require 'smccrawler/employee_state_extractor/id'
# require 'smccrawler/employee_state_extractor/il'
# require 'smccrawler/employee_state_extractor/in'
# require 'smccrawler/employee_state_extractor/ks'
# require 'smccrawler/employee_state_extractor/ma'
# require 'smccrawler/employee_state_extractor/md'
# require 'smccrawler/employee_state_extractor/mi'
# require 'smccrawler/employee_state_extractor/mn'
# require 'smccrawler/employee_state_extractor/mo'
# require 'smccrawler/employee_state_extractor/mt'
# require 'smccrawler/employee_state_extractor/nc'
# require 'smccrawler/employee_state_extractor/nd'
# require 'smccrawler/employee_state_extractor/ne'
# require 'smccrawler/employee_state_extractor/nj'
# require 'smccrawler/employee_state_extractor/nm'
# require 'smccrawler/employee_state_extractor/nv'
# require 'smccrawler/employee_state_extractor/ny'
# require 'smccrawler/employee_state_extractor/oh'
# require 'smccrawler/employee_state_extractor/or'
# require 'smccrawler/employee_state_extractor/pa'
# require 'smccrawler/employee_state_extractor/ri'
# require 'smccrawler/employee_state_extractor/tn'
# require 'smccrawler/employee_state_extractor/tx'
# require 'smccrawler/employee_state_extractor/ut'
# require 'smccrawler/employee_state_extractor/va'
# require 'smccrawler/employee_state_extractor/vt'
# require 'smccrawler/employee_state_extractor/wa'
# require 'smccrawler/employee_state_extractor/wi'
# require 'smccrawler/employee_state_serializer/al'
# require 'smccrawler/employee_state_serializer/az'
# require 'smccrawler/employee_state_serializer/ca'
# require 'smccrawler/employee_state_serializer/co'
# require 'smccrawler/employee_state_serializer/ct'
# require 'smccrawler/employee_state_serializer/dc'
# require 'smccrawler/employee_state_serializer/de'
# require 'smccrawler/employee_state_serializer/fl'
# require 'smccrawler/employee_state_serializer/ga'
# require 'smccrawler/employee_state_serializer/ia'
# require 'smccrawler/employee_state_serializer/id'
# require 'smccrawler/employee_state_serializer/il'
# require 'smccrawler/employee_state_serializer/in'
# require 'smccrawler/employee_state_serializer/ks'
# require 'smccrawler/employee_state_serializer/ma'
# require 'smccrawler/employee_state_serializer/md'
# require 'smccrawler/employee_state_serializer/mi'
# require 'smccrawler/employee_state_serializer/mn'
# require 'smccrawler/employee_state_serializer/mo'
# require 'smccrawler/employee_state_serializer/mt'
# require 'smccrawler/employee_state_serializer/nc'
# require 'smccrawler/employee_state_serializer/nd'
# require 'smccrawler/employee_state_serializer/ne'
# require 'smccrawler/employee_state_serializer/nj'
# require 'smccrawler/employee_state_serializer/nm'
# require 'smccrawler/employee_state_serializer/nv'
# require 'smccrawler/employee_state_serializer/ny'
# require 'smccrawler/employee_state_serializer/oh'
# require 'smccrawler/employee_state_serializer/or'
# require 'smccrawler/employee_state_serializer/pa'
# require 'smccrawler/employee_state_serializer/ri'
# require 'smccrawler/employee_state_serializer/tn'
# require 'smccrawler/employee_state_serializer/tx'
# require 'smccrawler/employee_state_serializer/ut'
# require 'smccrawler/employee_state_serializer/va'
# require 'smccrawler/employee_state_serializer/vt'
# require 'smccrawler/employee_state_serializer/wa'
# require 'smccrawler/employee_state_serializer/wi'
require_relative 'smccrawler/page/base'
# require 'smccrawler/page/client_list_page'
# require 'smccrawler/page/company_employee_details_report_page'
# require 'smccrawler/page/employee_list_page'
# require 'smccrawler/page/employee/employee_basics_page'
# require 'smccrawler/page/employee/employee_deductions_contributions_page'
# require 'smccrawler/page/employee/employee_employment_page'
# require 'smccrawler/page/employee/employee_pay_page'
# require 'smccrawler/page/employee/employee_taxes_exemptions_page'
# require 'smccrawler/page/employee/employee_vacation_sick_pay_page'
# require 'smccrawler/page/employee_review_page'
require_relative 'smccrawler/page/login'
require_relative 'smccrawler/page/archive'
require_relative 'smccrawler/crawler'
require_relative 'smccrawler/data_store'
require_relative 'smccrawler/errors'
require_relative 'smccrawler/serializer'

module Smccrawler
end